### ISSUE TITLE
Support installation for Pop OS

### ISSUE THREAD

**Issue by gviamont** [RedisTimeSeries/RedisTimeSeries#447]
Pop OS is a fork of Ubuntu that is installed by default on System 76 machines.  I was able to trivially get RedistTimeSeries to install with a couple of minor changes.  Without the changes diff'd below, make setup fails in the following two places:

Traceback (most recent call last):
  File "./system-setup.py", line 51, in <module>
    RedisTimeSeriesSetup(nop = args.nop).setup()
  File "./deps/readies/paella/setup.py", line 88, in setup
    RepoRefresh(self.runner).invoke()
  File "./deps/readies/paella/platform.py", line 201, in invoke
    assert(False), "Cannot determine installer"
AssertionError: Cannot determine installer
make: *** [Makefile:23: setup] Error 1

/usr/bin/python2 -m pip --version
/usr/bin/python2: No module named pip
command failed: /usr/bin/python2 -m pip --version
Traceback (most recent call last):
  File "./system-setup.py", line 51, in <module>
    RedisTimeSeriesSetup(nop = args.nop).setup()
  File "./deps/readies/paella/setup.py", line 89, in setup
    self.invoke()
  File "./deps/readies/paella/platform.py", line 168, in invoke
    self.common_first()
  File "./system-setup.py", line 17, in common_first
    self.setup_pip()
  File "./deps/readies/paella/setup.py", line 219, in setup_pip
    self.install_downloaders()
  File "./deps/readies/paella/setup.py", line 225, in install_downloaders
    self.install("ca-certificates", _try=_try)
  File "./deps/readies/paella/setup.py", line 142, in install
    Assert(False), "Cannot determine installer"
NameError: global name 'Assert' is not defined
make: *** [Makefile:23: setup] Error 1

Here's a hack I threw in which fixed the issue and allowed me to install on Pop OS.  There is likely a more elegant way to do this, but this communicates the idea I believe:

diff --git a/paella/platform.py b/paella/platform.py
index a7de60d..da03d50 100755
--- a/paella/platform.py
+++ b/paella/platform.py
@@ -181,7 +181,7 @@ class OnPlatform:
 
                 if dist == 'fedora':
                     self.fedora()
-                elif dist == 'ubuntu':
+                elif dist == 'ubuntu' or dist == 'pop':
                     self.ubuntu()
                 elif dist == 'debian':
                     self.debian()
diff --git a/paella/setup.py b/paella/setup.py
index f54c96d..7b852ee 100755
--- a/paella/setup.py
+++ b/paella/setup.py
@@ -130,7 +130,7 @@ class Setup(OnPlatform):
         if self.os == 'linux':
             if self.dist == 'fedora': # also include centos 8
                 self.dnf_install(packs, group=group, _try=_try)
-            elif self.platform.is_debian_compat():
+            elif self.platform.is_debian_compat() or self.dist == 'pop':
                 self.apt_install(packs, group=group, _try=_try)
             elif self.platform.is_redhat_compat():
                 self.yum_install(packs, group=group, _try=_try)

**Comment by gviamont** [comment]
I figure the contents of /etc/os-release may be of use as well:

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Comment by rafie** [comment]
Thanks for the feedback!
I thing we'll introduce Pop OS support in few levels:
(1) Enable `is-debian-compat()` via the `ID_LIKE` setting,
(2) Let `system-system.py` accept `--osnick` argument to override auto-detection,
(3) Use an embedded `distro` package for 2nd-line auto-detection.

BTW, is there by any chance a Pop! OS docker container available? (did not find any in Dockerhub).

**Comment by gviamont** [comment]
Hi @rafie this sounds very reasonable.  I poked around Dockerhub and could not find a container for Pop! OS there either.  When I get a chance I'll drop the System76 support group a request to create an official container there if that would be helpful.

**Comment by AlexMikhalev** [comment]
Bump. As paela shared with RedisGears, I reached the same point when trying to compile RedisGears on Pop OS. osnick to system-system.py sounds good or expanding in readme what make setup actually trying to install will do. 
Pop OS is pretty much the only way to get a decent user experience on a laptop with Nvidia RTX card, I would expect more people to come here.

**Comment by rafie** [comment]
@AlexMikhalev I've recently added support for Ubuntu-compatible OSes in readies/paella. 
Basically `./deps/readies/bin/platform` should now identify the system as the underlying Ubuntu, which will enable the installations to complete.
It should be reflected in RedisTimeSeries very soon (PR #545).
I will later add an `--brand` option, which will report the brand values.

**Comment by AlexMikhalev** [comment]
Thank you, @rafie. Looking forward to it.
A

**Comment by danni-m** [comment]
@rafie @AlexMikhalev can we close this issue?

**Comment by rafie** [comment]
@danni-m Fix was merged, ok to close.

**Comment by AlexMikhalev** [comment]
@rafie are we working with master? 
I still have the same error.
